<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <!-- 单击进不去，可以重新导入该Maven项目以下 -->
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>3.5.13</version>
        <relativePath/> <!-- lookup parent from repository -->
    </parent>

    <groupId>com.wsw</groupId>
    <artifactId>j-spring-boot-study</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>pom</packaging>

    <properties>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <modules>
        <module>springboot-01-quickstart</module>
        <module>springboot-02-base-config</module>
        <module>springboot-03-read-data</module>
        <module>springboot-04-profile</module>
        <module>springboot-05-maven-and-boot-profile</module>
        <module>springboot-07-test</module>
        <module>springboot-08-mybatis</module>
        <module>springboot-09-ssm</module>
    </modules>

</project>