# 设置启用环境
spring:
  profiles:
    active: dev

---
# 开发环境
spring:
  config:
    activate:
      on-profile: dev
server:
  port: 8081
logging:
  level:
    root: info
---
# 生产环境
spring:
  config:
    activate:
      on-profile: pro
server:
  port: 8082
logging:
  level:
    root: info
---
# 测试环境
spring:
  config:
    activate:
      on-profile: test
server:
  port: 8083
logging:
  level:
    root: warn